version: "3"
services:
  db:
    image: mysql:8
    container_name: cirius-api.db
    ports:
      - "3011:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: UTC
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
